### ISSUE TITLE
Refreshing DAGs in UI seems broken

### ISSUE THREAD

**Issue by criccomini** [wepay/airflow-webserver#10]
I hit refresh on a DAG, and got a "fresh as a daisy" message. I waited >10 minutes, and the DAG is still not refreshed in the UI. It's in the state where I can't click on any of the tree view/graph view/etc, and when I hover over the "info" icon next to the DAG name, it says that the DAG is not in the web server's DagBag object, but is in the DB's metadata.

I think at some point the webserver should pick up the new DAG, but it never did.

**Comment by jgao54** [comment]
Turn out this was a bug from the old UI that got carried over.

Every dag has an attribute `full_filepath` where /refresh will reload for the dag file from. But if the dag is built with a builder imported from another module, the filepath points to the builder. Will see if this is a trivial fix.

**Comment by jgao54** [comment]
Tracked https://github.com/apache/incubator-airflow/pull/2863

**Comment by jgao54** [comment]
PR merged so this should be fixed in the next release.
