### ISSUE TITLE
Alert users when they can't toggle off a DAG

### ISSUE THREAD

**Issue by criccomini** [wepay/airflow-webserver#12]
As a viewer, if I try to toggle a DAG off, it appears to toggle off. Then I refresh, and it's on again. Having some kind of alert when I try to toggle the DAG off (and not allowing the toggle to flip) would be a better user experience.

**Comment by jgao54** [comment]
I've disabled the toggle for viewer role (ie. can no longer toggle via UI).
It's a bit simpler to implement than writing JS to handle the toggle alert.
