### ISSUE TITLE
Support URL Prefix

### ISSUE THREAD

**Issue by gsemet** [wepay/airflow-webserver#19]
Hello

I don't know if you have planned to support url prefix, but I wish you would consider it, so that you can have urls such as

   http://datascience.mycompany.com/airflow/

I try to bring it to the current UI ([airflow#2723](https://github.com/apache/incubator-airflow/pull/2723))
Thanks

**Comment by jgao54** [comment]
@Stibbons Thanks this is a great feature. I'm currently focusing on making airflow-webserver compatible with the latest airflow 1.9.0rc6 release (hopefully that's the final 1.9 stable release as well). and then will move on catching up to the latest master. Once your change in airflow#2723 is merged to master, and you want to get a head start on making this feature available in the new UI, happy to accept PR on it :D

**Comment by jgao54** [comment]
This feature is supported in the PR against Apache-Airflow. Turns out it didn't require much additional work :)
