### ISSUE TITLE
Dynamic DAG generation

### ISSUE THREAD

**Issue by xycloud** [wepay/airflow-webserver#30]
https://wecode.wepay.com/posts/airflow-wepay

where is the Dynamic DAG generation, is that opensourced?

**Comment by criccomini** [comment]
No, it's not open sourced. That is something that is fairly straight forward to build on your own. We generally have some form of a config file (e.g. .json, .properties, .yaml, etc), along with a .py file. The .py file loads the config file, and uses its configuration to generate one or more DAGs.

Here's an example of a .py file that uses a DagBuilder class to generate a bunch of DAGs from a CLUSTERS variable.

```
"""
An example dynamic DAG Python file.

Note: it is important for this file to contain the strings 'airflow' and 'DAG'
in it. This is how Airflow detects if it should scan a file for module
attributes that are instance of DAG. See DagBag.process_file for details.
"""

from db_config import CLUSTERS
from dag_builders import DbDagBuilder

# Build all of the DAGs.
dag_dict = DbDagBuilder(clusters=CLUSTERS).build()

# Inject the properties into the __dict__ for this module. This will allow
# airflow to pick up the DAGs.
globals().update(dag_dict)
```

**Comment by tedmiston** [comment]
Hey @criccomini - I've been doing something like this to generate dynamic DAGs, however, a little different.  I loop through config objects inside my DAG file creating DAG instances _but_ this comes with the cost of the core DAG processing loop only scheduling tasks for a particular instance of that DAG until all instances have been processed.  It's become a pain point as this DAG now has dozens of instances.

Does doing it the way you suggested with `DbDagBuilder` avoid this tradeoff for multiple instances of the same DAG?

**Comment by criccomini** [comment]
@tedmiston, TBH not sure. I'd recommend moving this discussion go the Airflow dev@ mailing list.
