### ISSUE TITLE
admin >> xcomms exception

### ISSUE THREAD

**Issue by Tagar** [wepay/airflow-webserver#6]
http://airflow.westus.cloudapp.azure.com:8080/xcom/list/

> File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
> return self.wsgi_app(environ, start_response)
> File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
> response = self.make_response(self.handle_exception(e))
> File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
> reraise(exc_type, exc_value, tb)
> File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
> response = self.full_dispatch_request()
>

**Comment by jgao54** [comment]
@Tagar the app is down and I can't replicate the exception on my end, could you provide more details?  thanks!

**Comment by Tagar** [comment]
@jgao54 yep I got a timeout too.. we may have to wait until @mistercrunch brings it back up :-)

**Comment by jgao54** [comment]
@Tagar I believe this is solved, please reopen if you see otherwise.
