### ISSUE TITLE
would be nice to preserve old look and feel

### ISSUE THREAD

**Issue by Tagar** [wepay/airflow-webserver#7]
It would be nice if new forms preserve old Airflow look and feel.

Have a look and compare for example 
http://airflow.westus.cloudapp.azure.com:8080/users/list/
and 
http://airflow.westus.cloudapp.azure.com:8080/home

I personally like the latter.

**Comment by jgao54** [comment]
@Tagar right now it's using flask-appbuilder's default UI. There are

**Comment by jgao54** [comment]
Right now it's using the default modelview provided by flask-appbuilder, which is slightly different from flask-admin's modelview (i.e. header, searchbar, filter). The current priority is making sure it's functionally equivalent with the old UI, so I'm not going to work on this any time soon. 

Contribution welcome though! :)
